name: dust_collector_mobile
description: "Ultimate Crypto Dust Sweeper Pro."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.11.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web3dart: ^2.7.3
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  bip39: ^1.0.6
  crypton: ^2.0.1
  logger: ^2.0.2
  bip32: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
